language: go

go:
  - 1.13.x

services:
  - elasticsearch

env:
  - ES_NODES=http://127.0.0.1:9200 CDB_DSN=postgresql://root@localhost:26257/linkgraph?sslmode=disable

before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.0-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.4.0-amd64.deb && sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch && sudo service elasticsearch restart
  - wget -qO- https://binaries.cockroachdb.com/cockroach-v19.1.2.linux-amd64.tgz | tar xvz && cockroach-v19.1.2.linux-amd64/cockroach start --insecure --background --advertise-addr 127.0.0.1:26257
  - cockroach-v19.1.2.linux-amd64/cockroach sql --insecure -e 'CREATE DATABASE linkgraph;'
  - cd "$GOPATH/src/github.com/PacktPublishing/Hands-On-Software-Engineering-with-Golang"
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
  - sleep 10

script:
  - GO111MODULE=off make ci-check
  - rm -Rf vendor/
  - GO111MODULE=on make ci-check

after_success:
  - bash <(curl -s https://codecov.io/bash)
