apiVersion: batch/v1
kind: Job
metadata:
  name: cdb-ensure-schema
  namespace: linksrus-data
spec:
  template:
    spec:
      containers:
      - name: cdb-schema
        imagePullPolicy: Always
        image: localhost:5000/cdb-schema:latest
        args: 
         - "linkgraph"
         - "cdb-cockroachdb-public.linksrus-data"
      restartPolicy: Never
